name: shadow-cljs CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npx shadow-cljs release :app
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.1
      with:
        # Build directory to deploy
        build_dir: public
